
CREATE TABLE public."Drivers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Available" boolean,
    "Latitude" double precision,
    "Longitude" double precision,
    CONSTRAINT "PK_Drivers" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Drivers"
    OWNER to postgres;


CREATE TABLE public."Passengers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Latitude" double precision,
    "Longitude" double precision,
    CONSTRAINT "PK_Passengers" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Passengers"
    OWNER to postgres;



CREATE TABLE public."Trips"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "PassengerId" integer NOT NULL,
    "DriverId" integer NOT NULL,
    "Start" timestamp without time zone NOT NULL,
    "End" timestamp without time zone,
    CONSTRAINT "PK_Trips" PRIMARY KEY ("Id"),
    CONSTRAINT fk_trips_drivers FOREIGN KEY ("DriverId")
        REFERENCES public."Drivers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT fk_trips_passenger FOREIGN KEY ("PassengerId")
        REFERENCES public."Passengers" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE public."Trips"
    OWNER to postgres;
-- Index: fki_fk_trips_drivers

-- DROP INDEX public.fki_fk_trips_drivers;

CREATE INDEX fki_fk_trips_drivers
    ON public."Trips" USING btree
    ("DriverId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: fki_fk_trips_passenger

-- DROP INDEX public.fki_fk_trips_passenger;

CREATE INDEX fki_fk_trips_passenger
    ON public."Trips" USING btree
    ("PassengerId" ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE TABLE public."Invoices"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TripId" integer,
    "Amount" money,
    "Created" timestamp without time zone,
    CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id"),
    CONSTRAINT fk_invoices_trips FOREIGN KEY ("TripId")
        REFERENCES public."Trips" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE public."Invoices"
    OWNER to postgres;
-- Index: fki_fk_invoices_trips

-- DROP INDEX public.fki_fk_invoices_trips;

CREATE INDEX fki_fk_invoices_trips
    ON public."Invoices" USING btree
    ("TripId" ASC NULLS LAST)
    TABLESPACE pg_default;

INSERT INTO public."Drivers"(
	"Name", "Available", "Latitude", "Longitude")
	VALUES ('First driver', true, 18.4923177, -69.8391991);

INSERT INTO public."Passengers"(
	 "Name", "Latitude", "Longitude")
	VALUES ('First passenger', 18.4867788, -69.8386928);
